// pages/index.tsx
import type { NextPage } from "next";
import Head from "next/head";
import styled from "styled-components";

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Headline>GYDIAR!</Headline>
            </main>
        </>
    );
};

export default Home;

const Headline = styled.h1`
    text-align: center;
    font-size: 10rem;
    margin-top: 300px;
`;
